version: '3.7'

networks:
  blesta:
    ipam:
      driver: default
      config:
        - subnet: 172.18.238.0/24

services:

  traefik:
    image: traefik:v2.2
    restart: always
    env_file:
      - .env
    networks:
      - blesta
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}/traefik/traefik.toml:/etc/traefik/traefik.toml

  app:
    image: blesta:latest
    restart: always
    env_file:
      - .env
    networks:
      blesta:
        ipv4_address: 172.18.238.5
    depends_on:
      - db
    volumes:
      - ${DATA_DIR}/blesta/html:/var/www/html
      - ${DATA_DIR}/blesta/uploads:/var/www/uploads
    labels:
      - "traefik.http.routers.blesta.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.blesta.tls=true"

  db:
    image: mariadb:10.5
    restart: always
    env_file:
      - .env
    networks:
     blesta:
    volumes:
      - ${DATA_DIR}/db:/var/lib/mysql
